- type: replace
  path: /instance_groups/name=master/jobs/-
  value:
    name: cloud-provider
    release: kubo
    properties:
      cloud-provider:
        type: openstack
        openstack:
          auth-url: ((auth_url))
          username: ((openstack_username))
          password: ((openstack_password))
          tenant-id: ((openstack_project_id))
          domain-name: ((openstack_domain))
    provides:
      cloud-provider: {as: master}
    consumes:
      cloud-provider: {from: worker}

- type: replace
  path: /instance_groups/name=master/jobs/name=kubernetes-roles/consumes?
  value:
    cloud-provider: {from: master}

- type: replace
  path: /instance_groups/name=worker/jobs/-
  value:
    name: cloud-provider
    release: kubo
    properties:
      cloud-provider:
        type: openstack
        openstack:
          auth-url: ((auth_url))
          username: ((openstack_username))
          password: ((openstack_password))
          tenant-id: ((openstack_project_id))
          domain-name: ((openstack_domain))
    provides:
      cloud-provider: {as: worker}
    consumes:
      cloud-provider: {from: worker}
