- label: kubo-windows
  path: /releases/name=kubo-windows?
  type: replace
  value:
    name: kubo-windows
    sha1: 94ab2ac55f736e75d4efa1deececb37251ee31b6
    url: https://github.com/cloudfoundry-incubator/kubo-release-windows/releases/download/v0.41.0/kubo-release-windows-0.41.0.tgz
    version: 0.41.0
- path: /stemcells/-
  type: replace
  value:
    alias: windows
    os: windows2019
    version: "2019.7"
- path: /instance_groups/-
  type: replace
  value:
    azs:
    - z1
    - z2
    - z3
    instances: 3
    jobs:
    - name: kubelet-windows
      properties:
        api-token: ((kubelet-password))
        drain-api-token: ((kubelet-drain-password))
        k8s-args:
          cni-bin-dir: C:\var\vcap\jobs\kubelet-windows\packages\cni-windows\bin
          container-runtime: docker
          image-pull-progress-deadline: 20m
          kubeconfig: C:\var\vcap\jobs\kubelet-windows\config\kubeconfig
          network-plugin: cni
          pod-infra-container-image: mcr.microsoft.com/k8s/core/pause:1.2.0
          register-with-taints: windows=2019:NoSchedule
          resolv-conf: ""
        kubelet-configuration:
          apiVersion: kubelet.config.k8s.io/v1beta1
          authentication:
            anonymous:
              enabled: false
            x509:
              clientCAFile: C:\var\vcap\jobs\kubelet-windows\config\kubelet-client-ca.pem
          authorization:
            mode: Webhook
          cgroupsPerQOS: false
          clusterDNS:
          - 10.100.200.10
          clusterDomain: cluster.local
          enforceNodeAllocatable: []
          failSwapOn: false
          kind: KubeletConfiguration
          readOnlyPort: 0
          serializeImagePulls: false
          tlsCertFile: C:\var\vcap\jobs\kubelet-windows\config\kubelet.pem
          tlsPrivateKeyFile: C:\var\vcap\jobs\kubelet-windows\config\kubelet-key.pem
        tls:
          kubelet: ((tls-kubelet))
          kubelet-client-ca:
            certificate: ((tls-kubelet-client.ca))
          kubernetes: ((tls-kubernetes))
      release: kubo-windows
    - consumes:
        flanneld:
          from: worker-flanneld
      name: flanneld-windows
      properties:
        tls:
          etcdctl:
            ca: ((tls-etcdctl-flanneld.ca))
            certificate: ((tls-etcdctl-flanneld.certificate))
            private_key: ((tls-etcdctl-flanneld.private_key))
      release: kubo-windows
    - name: kube-proxy-windows
      properties:
        api-token: ((kube-proxy-password))
        kube-proxy-configuration:
          apiVersion: kubeproxy.config.k8s.io/v1alpha1
          clientConnection:
            kubeconfig: /var/vcap/jobs/kube-proxy-windows/config/kubeconfig
          clusterCIDR: 10.200.0.0/16
          kind: KubeProxyConfiguration
          mode: kernelspace
          portRange: ""
        tls:
          kubernetes: ((tls-kubernetes))
      release: kubo-windows
    - name: docker-windows
      release: kubo-windows
    name: windows-worker
    networks:
    - name: default
    stemcell: windows
    vm_type: worker
- path: /addons/-
  type: replace
  value:
    include:
      stemcell:
      - os: windows2019
    jobs:
    - name: kubo-dns-aliases
      release: kubo
    name: bosh-dns-aliases-windows
