- type: replace
  path: /instance_groups/name=master/jobs/-
  value:
    name: cloud-provider
    release: kubo
    properties:
      cloud-provider:
        type: gce
        gce:
          project-id: ((project_id))
          network-name: ((network))
          worker-node-tag: ((director_name))-((deployment_name))-worker
    provides:
      cloud-provider: {as: master-cloud-provider}

- type: replace
  path: /instance_groups/name=master/jobs/name=kube-apiserver/consumes?
  value:
    cloud-provider: {from: master-cloud-provider}

- type: replace
  path: /instance_groups/name=master/jobs/name=kube-controller-manager/consumes?
  value:
    cloud-provider: {from: master-cloud-provider}

- type: replace
  path: /instance_groups/name=master/jobs/name=kubernetes-roles/consumes?
  value:
    cloud-provider: {from: master-cloud-provider}

- type: replace
  path: /instance_groups/name=worker/jobs/-
  value:
    name: cloud-provider
    release: kubo
    properties:
      cloud-provider:
        type: gce
        gce:
          project-id: ((project_id))
          network-name: ((network))
          worker-node-tag: ((director_name))-((deployment_name))-worker
    provides:
      cloud-provider: {as: worker-cloud-provider}

- type: replace
  path: /instance_groups/name=worker/jobs/name=kubelet/consumes?
  value:
    cloud-provider: {from: worker-cloud-provider}

- type: replace
  path: /instance_groups/name=worker/jobs/name=kubelet/properties/cloud-provider?
  value: gce

- type: replace
  path: /instance_groups/name=worker/jobs/name=kube-proxy/properties/cloud-provider?
  value: gce

- type: replace
  path: /instance_groups/name=apply-addons/jobs/name=apply-specs/consumes?
  value:
    cloud-provider: {from: master-cloud-provider}
