- type: replace
  path: /instance_groups/name=master/jobs/-
  value:
    name: cloud-provider
    release: kubo
    properties:
      cloud-provider:
        type: vsphere
        vsphere:
          user: ((vcenter_master_user))
          password: ((vcenter_master_password))
          server: ((vcenter_ip))
          insecure-flag: 1
          datacenter: ((vcenter_dc))
          datastore: ((vcenter_ds))
          vms: ((vcenter_vms))
          working-dir: /((vcenter_dc))/vm/((vcenter_vms))/((director_uuid))
    provides:
      cloud-provider: {as: master}

- type: replace
  path: /instance_groups/name=master/jobs/name=kubernetes-roles/consumes?
  value:
    cloud-provider: {from: master}

- type: replace
  path: /instance_groups/name=worker/jobs/-
  value:
    name: cloud-provider
    release: kubo
    properties:
      cloud-provider:
        type: vsphere
        vsphere:
          user: ((vcenter_worker_user))
          password: ((vcenter_worker_password))
          server: ((vcenter_ip))
          insecure-flag: 1
          datacenter: ((vcenter_dc))
          datastore: ((vcenter_ds))
          vms: ((vcenter_vms))
          working-dir: /((vcenter_dc))/vm/((vcenter_vms))/((director_uuid))
