az: # Availability zone
subnet_id: # AWS Subnet ID
default_key_name: # AWS Key Name
default_security_groups: # Array of AWS Security Groups
region: # AWS Region ID
master_iam_instance_profile: # IAM Instance profile required by cloud provider on k8s master
worker_iam_instance_profile: # IAM Instance profile required by cloud provider on k8s worker
kubernetes_cluster_tag: # Tag to match public ELB subnet, Kubo workers subnet and Kubo worker VMs to make Kubernetes support ELB

# IaaS routing mode settings
# Comment out this section when using CF routing mode
routing_mode: iaas
kubernetes_master_host: # IP address that can be used to reach the Kubernetes API, usually the address of a load balancer or static IP
master_target_pool: # target pool that master nodes will be a part of
