platform: linux
image_resource:
  type: docker-image
  source:
    repository: pcfkubo/kubo-ci
    tag: stable
params:
  ROUTING_CF_CLIENT_SECRET:
  ROUTING_CF_NATS_INTERNAL_IP:
run:
  path: git-kubo-deployment/ci/scripts/deploy-k8s-instance.sh

inputs:
  - name: s3-kubo-release-tarball
  - name: git-kubo-deployment
  - name: s3-bosh-creds
  - name: kubo-lock
outputs:
  - name: service-creds
