name: ((deployment_name))

releases:
- name: etcd
  version: 108+dev.2
  url: https://storage.googleapis.com/kubo-etcd/kubo-etcd-release.108%2Bdev.2.tgz
  sha1: 6f452dae3d6399b38cbdee983847b81f88fc8163
- name: kubo
  version: latest
- name: docker
  version: 28.0.1
  url: https://bosh.io/d/github.com/cf-platform-eng/docker-boshrelease?v=28.0.1
  sha1: 448eaa2f478dc8794933781b478fae02aa44ed6b

stemcells:
- alias: trusty
  os: ubuntu-trusty
  version: ((stemcell_version))

instance_groups:
- name: etcd
  instances: 3
  networks:
  - name: &network-name ((deployments_network))
  azs: [z1]
  jobs:
  - name: etcd
    release: etcd
    properties:
      etcd:
        require_ssl: false
        peer_require_ssl: false
  stemcell: trusty
  vm_type: common
  persistent_disk_type: 5120

- name: master
  instances: 2
  networks:
  - name: *network-name
  azs: [z1]
  jobs:
  - name: kubernetes-api
    release: kubo
    properties:
      admin-username: admin
      admin-password: ((kubo-admin-password))
      kubelet-password: ((kubelet-password))
      tls:
        kubernetes: ((tls-kubernetes))
  - name: kubeconfig
    release: kubo
    properties:
      kubernetes-api-url: &kubo_url "https://((kubernetes_master_host)):8443"
      kubelet-password: ((kubelet-password))
      tls:
        kubernetes: ((tls-kubernetes))
  - name: kubernetes-controller-manager
    release: kubo
  - name: kubernetes-scheduler
    release: kubo
  - name: kubernetes-system-specs
    release: kubo
    properties:
      kubernetes-api-url: *kubo_url
  stemcell: trusty
  vm_type: master

- name: worker
  instances: 3
  networks:
  - name: *network-name
  azs: [z1]
  jobs:
  - name: flanneld
    release: kubo
  - name: docker
    release: docker
    properties:
      docker:
        flannel: true
        iptables: false
        ip_masq: false
        log_level: error
        storage_driver: overlay
      env: {}
  - name: kubeconfig
    release: kubo
    properties:
      kubernetes-api-url: *kubo_url
      kubelet-password: ((kubelet-password))
      tls:
        kubernetes: ((tls-kubernetes))
  - name: kubelet
    release: kubo
    properties:
      kubernetes-api-url: *kubo_url
      tls:
        kubelet: ((tls-kubelet))
  - name: kubernetes-proxy
    release: kubo
    properties:
      kubernetes-api-url: *kubo_url
  stemcell: trusty
  vm_type: worker
  persistent_disk_type: 10240

update:
  canaries: 1
  max_in_flight: 1
  serial: true
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000

variables:
- name: kubo-admin-password
  type: password
- name: kubelet-password
  type: password
- name: kubo_ca
  type: certificate
  options:
    is_ca: true
    common_name: ca
- name: tls-kubelet
  type: certificate
  options:
    ca: kubo_ca
    common_name: ((kubernetes_master_host))
    alternative_names: [((kubernetes_master_host))]
- name: tls-kubernetes
  type: certificate
  options:
    ca: kubo_ca
    common_name: ((kubernetes_master_host))
    alternative_names: [((kubernetes_master_host))]
