name: ((deployment_name))

releases:
- name: kubo-etcd
  version: 2
  url: https://storage.googleapis.com/kubo-public/kubo-etcd-2-ubuntu-trusty-3445.11-20170927-150426-34307934-20170927150432.tgz
  sha1: 90d5584a2e6dbe71b2675b6c7395bedb264969d2
- name: kubo
  version: latest
- name: docker
  version: 28.0.1
  url: https://storage.googleapis.com/kubo-public/docker-28.0.1-ubuntu-trusty-3445.11-20170927-150522-492831268-20170927150533.tgz
  sha1: 8b5df0aab503e04b1dde9ebd174f018d588400a2
- name: haproxy
  version: 8.4.0
  url: https://github.com/cloudfoundry-incubator/haproxy-boshrelease/releases/download/v8.4.0/haproxy-8.4.0.tgz
  sha1: a3a911f0cf8e672b27c6cb16318fd8c7c77f5bde

stemcells:
- alias: trusty
  os: ubuntu-trusty
  version: "3445.11"

instance_groups:
- name: etcd
  instances: 3
  networks:
  - name: &network-name ((deployments_network))
  azs: [z1]
  jobs:
  - name: etcd
    release: kubo-etcd
    properties:
      etcd:
        require_ssl: false
        peer_require_ssl: false
  stemcell: trusty
  vm_type: common
  persistent_disk_type: 5120

- name: master
  instances: 2
  networks:
  - name: *network-name
  azs: [z1]
  jobs:
  - name: cloud-provider
    release: kubo
    properties: {}
  - name: flanneld
    release: kubo
  - name: kubernetes-api
    release: kubo
    properties:
      admin-username: admin
      admin-password: ((kubo-admin-password))
      kubelet-password: ((kubelet-password))
      backend_port: 8443 # Bosh links hack
      port: ((kubernetes_master_port))
      tls:
        kubernetes: ((tls-kubernetes))
  - name: kubeconfig
    release: kubo
    properties:
      kubernetes-api-url: &kubo_url "https://((kubernetes_master_host)):((kubernetes_master_port))"
      kubelet-password: ((kubelet-password))
      tls:
        kubernetes: ((tls-kubernetes))
  - name: kubernetes-controller-manager
    release: kubo
    properties: {}
  - name: kubernetes-scheduler
    release: kubo
  - name: kubernetes-system-specs
    release: kubo
    properties:
      kubernetes-api-url: *kubo_url
  stemcell: trusty
  vm_type: master

- name: master-haproxy
  instances: 1
  networks:
  - name: ((deployments_network))
    default: [dns, gateway]
  azs: [z1]
  stemcell: trusty
  vm_type: common
  jobs:
  - name: haproxy
    release: haproxy

    consumes:
      tcp_backend: { from: master_haproxy }

    properties:
      ha_proxy:
        disable_http: true
        tcp_link_port: 9999 # required, but not used

- name: worker
  instances: 3
  networks:
  - name: *network-name
  azs: [z1]
  jobs:
  - name: use-ephemeral-storage-for-docker
    release: kubo
  - name: flanneld
    release: kubo
  - name: docker
    release: docker
    properties:
      docker:
        flannel: true
        iptables: false
        ip_masq: false
        log_level: error
        storage_driver: overlay
        default_ulimits: [ "nofile=65536" ]
      env: {}
  - name: kubeconfig
    release: kubo
    properties:
      kubernetes-api-url: *kubo_url
      kubelet-password: ((kubelet-password))
      tls:
        kubernetes: ((tls-kubernetes))
  - name: cloud-provider
    release: kubo
    properties: {}
  - name: kubelet
    release: kubo
    properties:
      kubernetes-api-url: *kubo_url
      tls:
        kubelet: ((tls-kubelet))
  - name: kubernetes-proxy
    release: kubo
    properties:
      kubernetes-api-url: *kubo_url
  stemcell: trusty
  vm_type: worker

update:
  canaries: 1
  max_in_flight: 1
  serial: true
  canary_watch_time: 10000-300000
  update_watch_time: 10000-300000

variables:
- name: kubo-admin-password
  type: password
- name: kubelet-password
  type: password
- name: kubo_ca
  type: certificate
  options:
    is_ca: true
    common_name: ca
- name: tls-kubelet
  type: certificate
  options:
    ca: kubo_ca
    common_name: ((kubernetes_master_host))
    alternative_names: [((kubernetes_master_host))]
- name: tls-kubernetes
  type: certificate
  options:
    ca: kubo_ca
    common_name: ((kubernetes_master_host))
    alternative_names:
    - ((kubernetes_master_host))
    - 10.100.200.1
    - kubernetes
    - kubernetes.default
    - kubernetes.default.svc
    - kubernetes.default.svc.cluster.local
