name: ((deployment_name))

releases:
- name: kubo-etcd
  version: 2
  url: https://storage.googleapis.com/kubo-public/kubo-etcd-2-ubuntu-trusty-3421.11-20170721-091603-591124789-20170721091609.tgz
  sha1: 91f7a6592ee6c5242854f3654fe786574e816ffc
- name: kubo
  version: latest
- name: docker
  version: 28.0.1
  url: https://storage.googleapis.com/kubo-public/docker-28.0.1-ubuntu-trusty-3421.11-20170720-164316-303456764-20170720164324.tgz
  sha1: 0ac80f013cc686047cdd7ccc428a8784c5e691bc
- name: haproxy
  url: https://storage.googleapis.com/kubo-public/haproxy-8.3.0-ubuntu-trusty-3421.11-20170721-091831-348952426-20170721091831.tgz
  sha1: 19f705d4958b24a4c49e9ec8770b5bee4ba454be
  version: latest

stemcells:
- alias: trusty
  os: ubuntu-trusty
  version: "3421.11"

instance_groups:
- name: etcd
  instances: 3
  networks:
  - name: &network-name ((deployments_network))
  azs: [z1]
  jobs:
  - name: etcd
    release: kubo-etcd
    properties:
      etcd:
        require_ssl: false
        peer_require_ssl: false
  stemcell: trusty
  vm_type: common
  persistent_disk_type: 5120

- name: master
  instances: 2
  networks:
  - name: *network-name
  azs: [z1]
  jobs:
  - name: cloud-provider
    release: kubo
    properties: {}
  - name: flanneld
    release: kubo
  - name: kubernetes-api
    release: kubo
    properties:
      admin-username: admin
      admin-password: ((kubo-admin-password))
      kubelet-password: ((kubelet-password))
      backend_port: 8443 # Bosh links hack
      port: ((kubernetes_master_port))
      tls:
        kubernetes: ((tls-kubernetes))
  - name: kubeconfig
    release: kubo
    properties:
      kubernetes-api-url: &kubo_url "https://((kubernetes_master_host)):((kubernetes_master_port))"
      kubelet-password: ((kubelet-password))
      tls:
        kubernetes: ((tls-kubernetes))
  - name: kubernetes-controller-manager
    release: kubo
    properties: {}
  - name: kubernetes-scheduler
    release: kubo
  - name: kubernetes-system-specs
    release: kubo
    properties:
      kubernetes-api-url: *kubo_url
  stemcell: trusty
  vm_type: master

- name: master-haproxy
  instances: 1
  networks:
  - name: ((deployments_network))
    default: [dns, gateway]
  azs: [z1]
  stemcell: trusty
  vm_type: common
  jobs:
  - name: haproxy
    release: haproxy

    consumes:
      tcp_backend: { from: master_haproxy }

    properties:
      ha_proxy:
        disable_http: true
        tcp_link_port: 9999 # required, but not used

- name: worker
  instances: 3
  networks:
  - name: *network-name
  azs: [z1]
  jobs:
  - name: flanneld
    release: kubo
  - name: docker
    release: docker
    properties:
      docker:
        flannel: true
        iptables: false
        ip_masq: false
        log_level: error
        storage_driver: overlay
      env: {}
  - name: kubeconfig
    release: kubo
    properties:
      kubernetes-api-url: *kubo_url
      kubelet-password: ((kubelet-password))
      tls:
        kubernetes: ((tls-kubernetes))
  - name: cloud-provider
    release: kubo
    properties: {}
  - name: kubelet
    release: kubo
    properties:
      kubernetes-api-url: *kubo_url
      tls:
        kubelet: ((tls-kubelet))
  - name: kubernetes-proxy
    release: kubo
    properties:
      kubernetes-api-url: *kubo_url
  stemcell: trusty
  vm_type: worker
  persistent_disk_type: 10240

update:
  canaries: 1
  max_in_flight: 1
  serial: true
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000

variables:
- name: kubo-admin-password
  type: password
- name: kubelet-password
  type: password
- name: kubo_ca
  type: certificate
  options:
    is_ca: true
    common_name: ca
- name: tls-kubelet
  type: certificate
  options:
    ca: kubo_ca
    common_name: ((kubernetes_master_host))
    alternative_names: [((kubernetes_master_host))]
- name: tls-kubernetes
  type: certificate
  options:
    ca: kubo_ca
    common_name: ((kubernetes_master_host))
    alternative_names:
    - ((kubernetes_master_host))
    - 10.100.200.1
    - kubernetes
    - kubernetes.default
    - kubernetes.default.svc
    - kubernetes.default.svc.cluster.local
