---
azs:
- name: z1
  cloud_properties:
    datacenters:
    - clusters: [((vcenter_cluster)): { resource_pool: ((vcenter_rp))}]

networks:
- name: &cloud_network ((deployments_network))
  type: manual
  subnets:
  - range: ((internal_cidr))
    gateway: ((internal_gw))
    dns: [((dns_recursor_ip))]
    azs: [z1]
    cloud_properties:
      name: ((network_name))
    reserved: ((reserved_ips))
    static: []

vm_types:
- name: common
  cloud_properties:
    ram: 4096
    cpu: 1
    disk: 20480

- name: master
  cloud_properties:
    ram: 4096
    cpu: 1
    disk: 20480

- name: worker
  cloud_properties:
    ram: 8192
    cpu: 4
    disk: 102400

disk_types:
- name: 10240
  disk_size: 10240
- name: 5120
  disk_size: 5120

compilation:
  workers: 4
  network: *cloud_network
  az: z1
  reuse_compilation_vms: true
  vm_type: worker
