---
azs:
- name: z1
  cloud_properties:
    datacenters:
    - clusters: [((vcenter_cluster)): {}]

networks:
- name: &network_name ((deployments_network))
  type: manual
  subnets:
  - range: ((internal_cidr))
    gateway: ((internal_gw))
    dns: [((internal_ip))]
    azs: [z1]
    cloud_properties:
      name: ((network_name))
    reserved: ((reserved_ips))

vm_types:
- name: common
  cloud_properties:
    ram: 4096
    cpu: 1
    disk: 20480

- name: worker
  cloud_properties:
    ram: 8192
    cpu: 1
    disk: 102400

disk_types:
- name: 10240
  disk_size: 10240
- name: 5120
  disk_size: 5120

compilation:
  workers: 4
  network: *network_name
  az: z1
  reuse_compilation_vms: true
  vm_type: worker
