---
azs:
- name: z1
  cloud_properties:
    zone: ((zone))

networks:
- name: default
  type: dynamic
  subnets:
  - range: ((internal_cidr))
    gateway: ((internal_gw))
    dns:
    - ((dns_recursor_ip))
    az: z1
    cloud_properties:
      network_name: ((network))
      subnetwork_name: ((subnetwork))
      ephemeral_external_ip: false

vm_types:
- name: minimal
  cloud_properties:
    machine_type: n1-standard-1
    root_disk_size_gb: 20
    root_disk_type: pd-ssd
    tags: ((tags))

- name: master
  cloud_properties:
    machine_type: n1-standard-1
    root_disk_size_gb: 20
    root_disk_type: pd-ssd
    service_account: ((service_account_master))
    tags: ((tags))

- name: worker
  cloud_properties:
    machine_type: n1-standard-2
    root_disk_size_gb: 100
    root_disk_type: pd-ssd
    service_account: ((service_account_worker))
    tags: ((tags))

compilation:
  workers: 4
  network: default
  az: z1
  reuse_compilation_vms: true
  vm_type: worker
