- type: replace
  path: /instance_groups/name=master/jobs/-
  value:
    name: cloud-provider
    release: kubo
    properties:
      cloud-provider:
        type: azure
        azure:
          cloud: ((azure_cloud_name))
          subscription-id: ((subscription_id))
          tenant-id: ((tenant_id))
          service-principal-id: ((client_id))
          service-principal-secret: ((client_secret))
          location: ((location))
          resource-group-name: ((resource_group_name))
          vnet-resource-group-name: ((vnet_resource_group_name))
          vnet-name: ((vnet_name))
          subnet-name: ((subnet_name))
          network-security-group-name: ((default_security_group))
          availability-set: ((primary_availability_set))

    provides:
      cloud-provider: {as: master-cloud-provider}

- type: replace
  path: /instance_groups/name=master/jobs/name=kube-apiserver/consumes?
  value:
    cloud-provider: {from: master-cloud-provider}

- type: replace
  path: /instance_groups/name=master/jobs/name=kube-controller-manager/consumes?
  value:
    cloud-provider: {from: master-cloud-provider}

- type: replace
  path: /instance_groups/name=master/jobs/name=kubernetes-roles/consumes?
  value:
    cloud-provider: {from: master-cloud-provider}

- type: replace
  path: /instance_groups/name=apply-addons/jobs/name=apply-specs/consumes?
  value:
    cloud-provider: {from: master-cloud-provider}

- type: replace
  path: /instance_groups/name=worker/jobs/-
  value:
    name: cloud-provider
    release: kubo
    properties:
      cloud-provider:
        type: azure
        azure:
          cloud: ((azure_cloud_name))
          subscription-id: ((subscription_id))
          tenant-id: ((tenant_id))
          service-principal-id: ((client_id))
          service-principal-secret: ((client_secret))
          location: ((location))
          resource-group-name: ((resource_group_name))
          vnet-resource-group-name: ((vnet_resource_group_name))
          vnet-name: ((vnet_name))
          subnet-name: ((subnet_name))
          network-security-group-name: ((default_security_group))
          availability-set: ((primary_availability_set))
    provides:
      cloud-provider: {as: worker-cloud-provider}

- type: replace
  path: /instance_groups/name=worker/jobs/name=kubelet/consumes?
  value:
    cloud-provider: {from: worker-cloud-provider}

- type: replace
  path: /instance_groups/name=worker/jobs/name=kubelet/properties/cloud-provider?
  value: azure

- type: replace
  path: /instance_groups/name=worker/jobs/name=kube-proxy/properties/cloud-provider?
  value: azure