- type: replace
  path: /instance_groups/name=master/jobs/-
  value:
    name: cloud-provider
    release: kubo
    properties:
      cloud-provider:
        type: aws
    provides:
      cloud-provider: {as: master}
    consumes:
      cloud-provider: {from: worker}

- type: replace
  path: /instance_groups/name=worker/jobs/-
  value:
    name: cloud-provider
    release: kubo
    properties:
      cloud-provider:
        type: aws
    provides:
      cloud-provider: {as: worker}
    consumes:
      cloud-provider: {from: worker}
