- type: remove
  path: /variables/name=tls-kubelet/options/organization
- type: remove
  path: /variables/name=tls-kubelet-client/options/organization
- type: remove
  path: /variables/name=tls-kubernetes/options/organization
