---
resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest

resources:
- name: git-kubo-deployment
  type: git
  source:
    uri: git@github.com:pivotal-cf-experimental/kubo-deployment
    branch: {{branch-name}}
    private_key: {{git-ssh-key}}

- name: git-kubo-release
  type: git
  source:
    uri: git@github.com:pivotal-cf-experimental/kubo-release
    branch: master
    private_key: {{git-ssh-key}}

- name: kubo-lock
  type: pool
  source:
    uri: git@github.com:pivotal-cf-experimental/kubo-locks.git
    branch: master
    private_key: {{git-ssh-key}}
    pool: kubo-deployment

- name: s3-bosh-state
  type: s3
  source:
    access_key_id: {{aws-access-key-id}}
    secret_access_key: {{aws-secret-access-key}}
    bucket: kubo-pipeline-store
    endpoint: s3-eu-west-1.amazonaws.com
    region_name: eu-west-1
    versioned_file: bosh/state.json

- name: s3-bosh-creds
  type: s3
  source:
    access_key_id: {{aws-access-key-id}}
    secret_access_key: {{aws-secret-access-key}}
    bucket: kubo-pipeline-store
    endpoint: s3-eu-west-1.amazonaws.com
    region_name: eu-west-1
    versioned_file: bosh/creds.yml

- name: s3-service-creds
  type: s3
  source:
    access_key_id: {{aws-access-key-id}}
    secret_access_key: {{aws-secret-access-key}}
    bucket: kubo-pipeline-store
    endpoint: s3-eu-west-1.amazonaws.com
    region_name: eu-west-1
    versioned_file: bosh/service-ci-service-creds.yml

- name: s3-kubo-release-tarball-tmp
  type: s3
  source:
    access_key_id: {{aws-access-key-id}}
    secret_access_key: {{aws-secret-access-key}}
    bucket: kubo-pipeline-store
    endpoint: s3-eu-west-1.amazonaws.com
    region_name: eu-west-1
    regexp: kubo-release-(.*).tgz

- name: s3-kubo-releases
  type: s3
  source:
    access_key_id: {{aws-access-key-id}}
    secret_access_key: {{aws-secret-access-key}}
    bucket: kubo-releases
    endpoint: s3-eu-west-1.amazonaws.com
    region_name: eu-west-1
    regexp: current-branch/kubo-release-(.*).tgz

- name: s3-kubo-deployments
  type: s3
  source:
    access_key_id: {{aws-access-key-id}}
    secret_access_key: {{aws-secret-access-key}}
    bucket: kubo-releases
    endpoint: s3-eu-west-1.amazonaws.com
    region_name: eu-west-1
    regexp: current-branch/kubo-deployment-(.*).tgz

- name: s3-kubo-release-tarball
  type: s3
  source:
    access_key_id: {{aws-access-key-id}}
    secret_access_key: {{aws-secret-access-key}}
    bucket: kubo-public
    endpoint: s3.amazonaws.com
    versioned_file: custom-build-kubo-release-latest.tgz

- name: s3-kubo-deployment-tarball
  type: s3
  source:
    access_key_id: {{aws-access-key-id}}
    secret_access_key: {{aws-secret-access-key}}
    bucket: kubo-public
    endpoint: s3.amazonaws.com
    versioned_file: custom-build-kubo-deployment-latest.tgz

- name: kubo-version
  type: semver
  source:
    key: kubo-version
    access_key_id: {{aws-access-key-id}}
    secret_access_key: {{aws-secret-access-key}}
    bucket: kubo-pipeline-store
    endpoint: s3-eu-west-1.amazonaws.com
    region_name: eu-west-1

- name: slack-alert
  type: slack-notification
  source:
    url: {{slack-url}}

jobs:
- name: claim-lock
  max_in_flight: 1
  plan:
  - aggregate:
    - get: git-kubo-release
    - get: git-kubo-deployment
  - put: kubo-lock
    params: { acquire: true }
  - put: kubo-version
    params:
      pre: dev

- name: install-bosh
  plan:
  - get: git-kubo-deployment
  - get: git-kubo-release
    passed: [ 'claim-lock' ]
  - get: kubo-lock
    version: every
    trigger: true
    passed: [ 'claim-lock' ]
  - get: kubo-version
    passed: [ 'claim-lock' ]
  - task: install
    file: git-kubo-deployment/ci/tasks/install-bosh.yml
    params:
      GCP_SERVICE_ACCOUNT: {{gcp-service-account}}
    on_failure:
      put: slack-alert
      params:
        silent: true
        icon_emoji: ":octopus:"
        text: |
          Deploy BOSH on {{branch-name}} failed:
          https://p-concourse.kubo.cf-app.com/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
  - aggregate:
    - put: s3-bosh-creds
      params:
        file: bosh-creds/creds.yml
    - put: s3-bosh-state
      params:
        file: bosh-state/state.json

- name: build-kubo-release
  plan:
  - aggregate:
    - get: kubo-lock
      version: every
      trigger: true
      passed: [ 'install-bosh' ]
    - get: git-kubo-deployment
      trigger: true
      passed: [ 'install-bosh' ]
    - get: kubo-version
      passed: [ 'install-bosh' ]
    - get: git-kubo-release
      passed: [ 'install-bosh' ]
    - get: s3-bosh-creds
      passed: [ 'install-bosh' ]
    - get: s3-bosh-state
      passed: [ 'install-bosh' ]
  - task: build-kubo-release
    file: git-kubo-deployment/ci/tasks/build-kubo-release.yml
    on_failure:
      put: slack-alert
      params:
        silent: true
        icon_emoji: ":thumbsdown:"
        text: |
          Kubo release build  on {{branch-name}} failed:
          https://p-concourse.kubo.cf-app.com/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
  - put: s3-kubo-release-tarball-tmp
    params:
      file: kubo-release/kubo-release-*.tgz

- name: deploy-k8s
  plan:
  - aggregate:
    - get: kubo-lock
      version: every
      trigger: true
      passed: [ 'build-kubo-release' ]
    - get: git-kubo-deployment
    - get: git-kubo-release
      passed: [ 'build-kubo-release' ]
    - get: kubo-version
      passed: [ 'build-kubo-release' ]
    - get: s3-bosh-state
      passed: [ 'build-kubo-release' ]
    - get: s3-bosh-creds
      passed: [ 'build-kubo-release' ]
    - get: s3-kubo-release-tarball-tmp
      passed: [ 'build-kubo-release' ]
  - task: deploy
    file: git-kubo-deployment/ci/tasks/deploy-k8s-instance.yml
    params:
      ROUTING_CF_CLIENT_SECRET: {{routing_cf_client_secret}}
    on_failure:
      put: slack-alert
      params:
        silent: true
        icon_emoji: ":octopus:"
        text: |
          Deploy K8s on branch {{branch-name}} failed:
          https://p-concourse.kubo.cf-app.com/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
  - put: s3-service-creds
    params:
      file: service-creds/service-ci-service-creds.yml

- name: deploy-workload
  plan:
  - aggregate:
    - get: kubo-lock
      version: every
      trigger: true
      passed: [ 'deploy-k8s' ]
    - get: git-kubo-deployment
    - get: s3-bosh-state
      passed: [ 'deploy-k8s' ]
    - get: s3-bosh-creds
      passed: [ 'deploy-k8s' ]
    - get: kubo-version
      passed: [ 'deploy-k8s' ]
    - get: git-kubo-release
      passed: [ 'deploy-k8s' ]
    - get: s3-service-creds
      passed: [ 'deploy-k8s' ]
    - get: s3-kubo-release-tarball-tmp
      passed: [ 'deploy-k8s' ]
  - task: workload
    file: git-kubo-deployment/ci/tasks/deploy-k8s-workload.yml
    on_failure:
      put: slack-alert
      params:
        silent: true
        icon_emoji: ":octopus:"
        text: |
          Deploy K8s Workload on branch {{branch-name}} failed:
          https://p-concourse.kubo.cf-app.com/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME

- name: destroy-k8s
  plan:
  - aggregate:
    - get: kubo-lock
      version: every
      trigger: true
      passed: [ 'deploy-workload' ]
    - get: kubo-version
      passed: [ 'deploy-workload' ]
    - get: git-kubo-deployment
    - get: s3-bosh-state
      passed: [ 'deploy-workload' ]
    - get: s3-bosh-creds
      passed: [ 'deploy-workload' ]
    - get: s3-kubo-release-tarball-tmp
      passed: [ 'deploy-workload' ]
  - task: destroy-k8s
    file: git-kubo-deployment/ci/tasks/destroy-k8s-instance.yml
    on_failure:
      put: slack-alert
      params:
        silent: true
        icon_emoji: ":octopus:"
        text: |
          Destroy K8s on branch {{branch-name}} failed:
          https://p-concourse.kubo.cf-app.com/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME


- name: destroy-bosh
  plan:
  - aggregate:
    - get: git-kubo-deployment
    - get: kubo-lock
      version: every
      trigger: true
      passed: [ 'destroy-k8s' ]
    - get: kubo-version
      passed: [ 'destroy-k8s' ]
    - get: s3-bosh-state
      passed: [ 'destroy-k8s' ]
    - get: s3-bosh-creds
      passed: [ 'destroy-k8s' ]
    - get: s3-kubo-release-tarball-tmp
      passed: [ 'destroy-k8s' ]
  - task: destroy
    file: git-kubo-deployment/ci/tasks/destroy-bosh.yml
    params:
      GCP_SERVICE_ACCOUNT: {{gcp-service-account}}
    on_failure:
      put: slack-alert
      params:
        silent: true
        icon_emoji: ":octopus:"
        text: |
          Destroy BOSH on branch {{branch-name}} failed:
          https://p-concourse.kubo.cf-app.com/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
  - put: kubo-lock
    params: { release: kubo-lock }

- name: upload-kubo-deployment
  plan:
  - aggregate:
    - get: git-kubo-deployment
      passed: [ destroy-bosh ]
      trigger: true
    - get: kubo-version
      passed: [ destroy-bosh ]
  - task: create-kubo-deployment-tarball
    file: git-kubo-deployment/ci/tasks/create-kubo-deployment-tarball.yml
  - aggregate:
    - put: s3-kubo-deployment-tarball
      params:
        file: tarballs/kubo-deployment-*.tgz
    - put: s3-kubo-deployments
      params:
        file: tarballs/kubo-deployment-*.tgz


- name: upload-kubo-release
  plan:
  - aggregate:
    - get: s3-kubo-release-tarball-tmp
      trigger: true
      passed: [ destroy-bosh ]
    - get: kubo-version
      passed: [ destroy-bosh ]
  - aggregate:
    - put: s3-kubo-release-tarball
      params:
        file: s3-kubo-release-tarball-tmp/kubo-release-*.tgz
    - put: s3-kubo-releases
      params:
        file: s3-kubo-release-tarball-tmp/kubo-release-*.tgz

- name: success-notification
  plan:
  - aggregate:
    - get: kubo-version
      passed: [ upload-kubo-release, upload-kubo-deployment ]
      trigger: true
  - put: slack-alert
    params:
      silent: true
      icon_emoji: ":chameleon:"
      text: |
        kubo-deployment pipeline on branch {{branch-name}} has succeeded
