azs:
- name: z1
  cloud_properties:
    datacenters:
    - clusters: [((vcenter_cluster)): {}]
- name: z2
  cloud_properties:
    datacenters:
    - clusters: [((vcenter_cluster)): {}]
- name: z3
  cloud_properties:
    datacenters:
    - clusters: [((vcenter_cluster)): {}]

vm_types:
- name: default
  cloud_properties:
    cpu: 2
    ram: 1024
    disk: 3240
- name: large
  cloud_properties:
    cpu: 2
    ram: 4096
    disk: 30_240

disk_types:
- name: default
  disk_size: 3000
- name: large
  disk_size: 50_000

networks:
- name: default
  type: manual
  subnets:
  - range: ((internal_cidr))
    gateway: ((internal_gw))
    azs: [z1, z2, z3]
    dns: [8.8.8.8]
    reserved: []
    cloud_properties:
      name: ((network_name))

compilation:
  workers: 5
  reuse_compilation_vms: true
  az: z1
  vm_type: default
  network: default
