- type: replace
  path: /instance_groups/name=master/jobs/name=kube-apiserver/properties/k8s-args/audit-log-maxage
  value: ((audit-log-maxage))

- type: replace
  path: /instance_groups/name=master/jobs/name=kube-apiserver/properties/k8s-args/audit-log-maxbackup
  value: ((audit-log-maxbackup))

- type: replace
  path: /instance_groups/name=master/jobs/name=kube-apiserver/properties/k8s-args/audit-log-maxsize
  value: ((audit-log-maxsize))


