- type: replace
  path: /instance_groups/name=master/jobs/name=kubernetes-api/properties/backend_port?
  value: ((master_haproxy_tcp_backend_port))

- type: replace
  path: /instance_groups/name=master/jobs/name=kubernetes-api/properties/port?
  value: ((master_haproxy_tcp_frontend_port))

- type: replace
  path: /instance_groups/name=master-haproxy/networks/0/static_ips
  value:
  - ((kubernetes-master-host))
