- path: /releases
  type: replace
  value:
  - name: kubo
    sha1: 81ca4a06f3280ab703567afc7ce408291ea5f6b6
    url: https://github.com/cloudfoundry-incubator/kubo-release/releases/download/v0.38.0/kubo-release-0.38.0.tgz
    version: 0.38.0
  - name: cfcr-etcd
    sha1: 5ff0104783202a287b7877883d9ff95f22e18eef
    url: https://bosh.io/d/github.com/cloudfoundry-incubator/cfcr-etcd-release?v=1.11.1
    version: 1.11.1
  - name: docker
    sha1: ee15b3dbb6f0e0d19f287e2cae22714f069f67f3
    url: https://bosh.io/d/github.com/cloudfoundry-incubator/docker-boshrelease?v=35.3.3
    version: 35.3.3
  - name: bpm
    sha1: 41df19697d6a69d2552bc2c132928157fa91abe0
    url: https://bosh.io/d/github.com/cloudfoundry-incubator/bpm-release?v=1.0.4
    version: 1.0.4
