- type: replace
  path: /variables/name=kubo_ca/options/duration?
  value: ((certificate-duration))

- type: replace
  path: /variables/name=tls-kubelet/options/duration?
  value: ((certificate-duration))

- type: replace
  path: /variables/name=tls-kubelet-client/options/duration?
  value: ((certificate-duration))

- type: replace
  path: /variables/name=tls-kubernetes/options/duration?
  value: ((certificate-duration))

- type: replace
  path: /variables/name=tls-kube-controller-manager/options/duration?
  value: ((certificate-duration))

- type: replace
  path: /variables/name=etcd_ca/options/duration?
  value: ((certificate-duration))

- type: replace
  path: /variables/name=tls-etcd-v0-29-0/options/duration?
  value: ((certificate-duration))

- type: replace
  path: /variables/name=tls-etcdctl-v0-29-0/options/duration?
  value: ((certificate-duration))

- type: replace
  path: /variables/name=tls-metrics-server/options/duration?
  value: ((certificate-duration))

- type: replace
  path: /variables/name=kubernetes-dashboard-ca/options/duration?
  value: ((certificate-duration))

- type: replace
  path: /variables/name=tls-kubernetes-dashboard/options/duration?
  value: ((certificate-duration))

